import streamlit as st
from core.coresignal_client import search_companies
from utils.env_loader import load_environment
from datetime import date
import pandas as pd
from core.coresignal_collect import collect_company

load_environment()

st.set_page_config(page_title="Company Search", layout="centered")
st.title("🔎 Advanced Company Filter")

# --- Static filter lists
company_sizes = [
    "2-10 employees",
    "11-50 employees",
    "51-200 employees",
    "201-500 employees",
    "501-1,000 employees",
    "1,001-5,000 employees",
    "5,001-10,000 employees",
    "5001-10,000 employees",
    "10,001+ employees"
]

industries = [
    "Real Estate",
    "Design Services",
    "Retail",
    "Chemical Manufacturing",
    "Broadcast Media Production and Distribution",
    "Telecommunications",
    "Retail Art Supplies",
    "Wholesale Import and Export",
    "Fine Art",
    "Information Technology & Services",
    "Advertising Services",
    "Food and Beverage Services",
    "Technology, Information and Internet",
    "E-learning",
    "Financial Services",
    "Non-profit Organizations",
    "Software Development",
    "Computer Networking Products",
    "Government Relations",
    "Packaging & Containers",
    "Education Administration Programs",
    "Capital Markets",
    "Manufacturing",
    "Higher Education",
    "Renewables & Environment",
    "Retail Apparel and Fashion",
    "Accounting",
    "Construction",
    "Law Practice",
    "Business Consulting and Services",
    "Alternative Medicine",
    "Agriculture, Construction, Mining Machinery Manufacturing",
    "Executive Offices",
    "Restaurants",
    "Online Audio and Video Media",
    "International Trade and Development",
    "Performing Arts",
    "Management Consulting",
    "Professional Training & Coaching",
    "IT Services and IT Consulting",
    "Environmental Services",
    "Music",
    "Food & Beverages",
    "Hospitality",
    "Internet",
    "Wholesale",
    "Oil and Gas",
    "Design",
    "Professional Training and Coaching",
    "Investment Management",
    "Apparel & Fashion",
    "Book and Periodical Publishing",
    "Information Services",
    "Mining",
    "Photography",
    "Transportation/Trucking/Railroad",
    "Appliances, Electrical, and Electronics Manufacturing",
    "Furniture and Home Furnishings Manufacturing",
    "Hospitals and Health Care",
    "Entertainment Providers",
    "Consumer Services",
    "Food Production",
    "Human Resources Services",
    "Staffing and Recruiting",
    "Machinery Manufacturing",
    "Wellness and Fitness Services",
    "Legal Services",
    "Civil Engineering",
    "Religious Institutions",
    "Transportation, Logistics, Supply Chain and Storage",
    "Public Relations and Communications Services",
    "Sports",
    "Events Services",
    "Artists and Writers",
    "Venture Capital and Private Equity Principals",
    "Medical Equipment Manufacturing",
    "Automotive",
    "Consumer Electronics",
    "Architecture and Planning",
    "Insurance",
    "Health, Wellness & Fitness",
    "Market Research",
    "Writing and Editing",
    "Media Production",
    "Musicians",
    "Personal Care Product Manufacturing",
    "Mental Health Care",
    "International Trade & Development",
    "Printing Services",
    "Biotechnology Research",
    "Motor Vehicle Manufacturing",
    "Computer Hardware",
    "Industrial Machinery Manufacturing",
    "Biotechnology",
    "Spectator Sports",
    "Retail Luxury Goods and Jewelry",
    "Movies, Videos, and Sound",
    "Wine & Spirits",
    "Philanthropic Fundraising Services",
    "Medical Device",
    "Plastics Manufacturing",
    "Entertainment",
    "Newspaper Publishing",
    "Education",
    "Travel Arrangements",
    "Law Enforcement",
    "Commercial Real Estate",
    "Renewable Energy Semiconductor Manufacturing",
    "Arts & Crafts",
    "International Affairs",
    "Banking",
    "Industrial Automation",
    "Dairy Product Manufacturing",
    "Human Resources",
    "Retail Office Equipment",
    "Truck Transportation",
    "Airlines and Aviation",
    "Packaging and Containers Manufacturing",
    "Defense & Space",
    "Beverage Manufacturing",
    "Graphic Design",
    "Automation Mach